(function () { 

	'use strict';

	/**
	 * @ngdoc function
	 * @name kinetixApp.controller:ProjectService
	 * @description
	 * # ProjectService
	 * Service of the projects for kinetixApp
	 */
	angular.module('kinetixApp')
	  .service('ProjectService', function(){
         /* jshint ignore:start */
          var projects = [{
              id: 1,
              slug: 'anglo-american-3d-annual-communications-summit',
              name: 'Anglo American 3d Annual Communications Summit',
              description: "<p>For the last 2 years Anglo American has held a global conference to bring together the marketing heads of all the wings in the organisation, aiming to consolidate and strategise a holistic strategy for the year to come. This year Cape Town was selected as the Venue and The Kinetic was brought on board to produce all the digital assets for the conference. Aiming to modernize the company, one of the key areas was the incorporation of an Ipad app rather than having a traditional printed conference program.</p> <p>Further more the delivery included a website for the conference, invitational emails sent out bi-weekly which each included a 1 minute video trailer to the event. The videos’ narratives were linked and built from one to the next. The culmination video including all the teasers along with a resolution message was screened at the conference opening along with on-screen content loops which ran throughout the conference.</p>",
              thumb: '../../images/projects/1/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/1/001.jpg',
                '../../images/projects/1/002.jpg',
                '../../images/projects/1/003.jpg',
                '../../images/projects/1/004.jpg',
                '../../images/projects/1/005.jpg',
                '../../images/projects/1/006.jpg',
                '../../images/projects/1/007.jpg',
                '../../images/projects/1/008.jpg',
                '../../images/projects/1/009.jpg',
                '../../images/projects/1/010.jpg',
                '../../images/projects/1/011.jpg',
                '../../images/projects/1/012.jpg',
                '../../images/projects/1/013.jpg',
                '../../images/projects/1/014.jpg',
                '../../images/projects/1/015.jpg',
                '../../images/projects/1/016.jpg',
                '../../images/projects/1/017.jpg',
                '../../images/projects/1/018.jpg',
                '../../images/projects/1/019.jpg',
                '../../images/projects/1/020.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Anglo American Comms Summit',
                  type : 'Show Package 1',
                  cover: '../../images/projects/1/018.jpg',
                  source: '119763015'
                },
                {
                  id : 2,
                  title : 'Anglo American Comms Summit',
                  type : 'Show Package 2',
                  cover: '../../images/video-cover.jpg',
                  source: '60631991'
                },
                {
                  id : 3,
                  title : 'Anglo American Comms Summit',
                  type : 'Show Package 3',
                  cover: '../../images/video-cover.jpg',
                  source: '60631991'
                }]
          },
          {
              id: 2,
              slug: 'armour',
              name: 'Armour',
              description: "<p>A visual identity inspired by bikes, beer and general badassness. The handmade feel of the Armour brand celebrates those who brew the beer they drink and build the bikes they ride.</p>",
              thumb: '../../images/projects/2/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/2/001.jpg',
                '../../images/projects/2/002.jpg',
                '../../images/projects/2/003.jpg',
                '../../images/projects/2/004.jpg',
                '../../images/projects/2/005.jpg',
                '../../images/projects/2/006.jpg',
                '../../images/projects/2/007.jpg',
                '../../images/projects/2/008.jpg',
                '../../images/projects/2/010.jpg',
                '../../images/projects/2/011.jpg',
                '../../images/projects/2/012.jpg',
                '../../images/projects/2/013.jpg',
                '../../images/projects/2/014.jpg',
                '../../images/projects/2/015.jpg',
                '../../images/projects/2/016.gif',
                '../../images/projects/2/017.jpg',
                '../../images/projects/2/018.jpg',
                '../../images/projects/2/019.gif',
                '../../images/projects/2/020.jpg',
                '../../images/projects/2/009.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Armour',
                  type : 'Branding and Design',
                  cover: '../../images/projects/2/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Branding and Design',
                  type : 'Show Package 3',
                  cover: '../../images/projects/2/cover.jpg',
                }]
          },
          {
              id: 3,
              slug: 'basa-awards',
              name: 'BASA Awards',
              description: "<p>The Business of the Arts South Africa is a non-profit organization that seeks to partner big business with local artists. An annual awards ceremony gives recognition to companies that have made a substantial and sustainable contribution to the arts, previous winners of this coveted award include Cell C, Deloitte and Absa.</p><p>It is a worthy cause and one that has over the years ensured a thriving culture of corporately funded artistic expression, adding to the already substantial body of world renowned work produced by South African artists. When we were asked to create a series of video pieces for the award ceremony, we were very excited to add our name to the long list of companies that support and believe in local art.</p>",
              thumb: '../../images/projects/3/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/3/001.jpg',
                '../../images/projects/3/002.jpg',
                '../../images/projects/3/003.jpg',
                '../../images/projects/3/004.jpg',
                '../../images/projects/3/005.jpg',
                '../../images/projects/3/006.jpg',
                '../../images/projects/3/007.jpg',
                '../../images/projects/3/008.jpg',
                '../../images/projects/3/009.jpg',
                '../../images/projects/3/010.jpg',
                '../../images/projects/3/011.jpg',
                '../../images/projects/3/012.jpg',
                '../../images/projects/3/013.jpg',
                '../../images/projects/3/014.jpg',
                '../../images/projects/3/015.jpg'
              ],
              videos : [
                {
                  id : 1,
                  title : 'BASA Awards',
                  type : 'Awards AV',
                  cover: '../../images/projects/3/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Awards AV',
                  type : 'Show Package 3',
                  cover: '../../images/projects/3/cover.jpg',
                }]
          },
          {
              id: 4,
              slug: 'samsung',
              name: 'Samsung',
              description: "<p>The Kinetic was approached by Breinstorm Brand Architects to create a series of AV projection elements for the Samsung Amaze Africa fashion show at the Pretoria City Hall. Each fashion designer was paired with an accessory designer and together they designed a line of fashion inspired by a specific type of fauna and flora found at the National Museum of Natural History across the road from where the show was held.<p></p>The AV elements also had to stem from this Natural object inspiration and were key in the creation of the lighting and overall show design.</p>",
              thumb: '../../images/projects/4/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/4/001.jpg',
                '../../images/projects/4/002.jpg',
                '../../images/projects/4/003.jpg',
                '../../images/projects/4/004.jpg',
                '../../images/projects/4/005.jpg',
                '../../images/projects/4/006.jpg',
                '../../images/projects/4/007.jpg',
                '../../images/projects/4/008.jpg',
                '../../images/projects/4/009.jpg',
                '../../images/projects/4/010.jpg',
                '../../images/projects/4/011.jpg',
                '../../images/projects/4/012.jpg',
                '../../images/projects/4/013.jpg',
                '../../images/projects/4/014.jpg',
                '../../images/projects/4/015.jpg',
                '../../images/projects/4/016.jpg',
                '../../images/projects/4/017.jpg',
                '../../images/projects/4/018.jpg',
                '../../images/projects/4/019.jpg',
                '../../images/projects/4/020.jpg',
                '../../images/projects/4/021.jpg',
                '../../images/projects/4/022.jpg',
                '../../images/projects/4/023.jpg',
                '../../images/projects/4/024.jpg',
                '../../images/projects/4/025.jpg',
                '../../images/projects/4/026.jpg',
                '../../images/projects/4/027.jpg',
                '../../images/projects/4/028.jpg',
                '../../images/projects/4/029.jpg',
                '../../images/projects/4/030.jpg',
                '../../images/projects/4/031.jpg',
                '../../images/projects/4/032.jpg',
                '../../images/projects/4/033.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Samsung',
                  type : 'Africa Fashion Week Event',
                  cover: '../../images/projects/4/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Samsung',
                  type : 'Africa Fashion Week Event',
                  cover: '../../images/projects/4/cover.jpg',
                }]
          },
          {
              id: 5,
              slug: 'cennergi',
              name: 'Cennergi',
              description: "<p>HKLM commissioned The Kinetic to produce a video for the launch of South Africa's new independant energy provider's brand reveal function. The aim being to showcase the brand’s vibrancy and to leave attendees with a deeper understanding and lasting excitement for Cennergi.</p><p>We also created a series of sponsor boards to coincide with the launch on broadcast television.</p>",
              thumb: '../../images/projects/5/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/5/001.jpg',
                '../../images/projects/5/002.jpg',
                '../../images/projects/5/003.jpg',
                '../../images/projects/5/004.jpg',
                '../../images/projects/5/005.jpg',
                '../../images/projects/5/006.jpg',
                '../../images/projects/5/007.jpg',
                '../../images/projects/5/008.jpg',
                '../../images/projects/5/009.jpg',
                '../../images/projects/5/010.jpg',
                '../../images/projects/5/011.jpg'
              ],
              videos : [
                {
                  id : 1,
                  title : 'Cennergi',
                  type : 'Launch AV',
                  cover: '../../images/projects/5/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Cennergi',
                  type : 'Launch AV',
                  cover: '../../images/projects/5/cover.jpg',
                }]
          },
          {
              id: 6,
              slug: 'battlecat',
              name: 'Battlecat!',
              description: "<p>Description still to come here</p>",
              thumb: '../../images/projects/6/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/6/1.jpg',
                '../../images/projects/6/2.jpg',
                '../../images/projects/6/3.jpg',
                '../../images/projects/6/4.jpg'
              ],
              videos : [
                {
                  id : 1,
                  title : 'Battlecat!',
                  type : 'Show Package 1',
                  cover: '../../images/projects/6/1.jpg',
                },
                {
                  id : 2,
                  title : 'Battlecat!',
                  type : 'Show Package 3',
                  cover: '../../images/projects/6/1.jpg',
                }]
          },
          {
              id: 7,
              slug: 'cancel-fashion',
              name: 'Cancel Fashion',
              description: "<p>Cancel is a collective of fashion designers and fashion event organisers, this project shows the brand development, photography and launch video of the Cancel fashion collective brand.</p>",
              thumb: '../../images/projects/7/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/7/001.jpg',
                '../../images/projects/7/002.jpg',
                '../../images/projects/7/003.jpg',
                '../../images/projects/7/004.jpg',
                '../../images/projects/7/005.jpg',
                '../../images/projects/7/006.jpg',
                '../../images/projects/7/007.jpg',
                '../../images/projects/7/008.jpg',
                '../../images/projects/7/009.jpg',
                '../../images/projects/7/010.jpg',
                '../../images/projects/7/011.jpg',
                '../../images/projects/7/012.jpg',
                '../../images/projects/7/013.jpg',
                '../../images/projects/7/014.jpg',
                '../../images/projects/7/015.jpg',
                '../../images/projects/7/016.jpg',
                '../../images/projects/7/017.jpg',
                '../../images/projects/7/018.jpg',
                '../../images/projects/7/019.jpg',
                '../../images/projects/7/020.jpg',
                '../../images/projects/7/021.jpg',
                '../../images/projects/7/022.jpg',
                '../../images/projects/7/023.jpg',
                '../../images/projects/7/024.jpg',
                '../../images/projects/7/025.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Cancel Fashion',
                  type : 'Branding, design and promo',
                  cover: '../../images/projects/7/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Cancel Fashion',
                  type : 'Branding, design and promo',
                  cover: '../../images/projects/7/cover.jpg',
                }]
          },
          {
              id: 8,
              slug: 'end-year-gift',
              name: 'Year End Gift',
              description: "<p>We made some extra special end year gifts in 2015 with the help of Hope On Hopkins in Cape Town, have a look.</p>",
              thumb: '../../images/projects/8/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/8/001.jpg',
                '../../images/projects/8/002.jpg',
                '../../images/projects/8/003.jpg',
                '../../images/projects/8/004.jpg',
                '../../images/projects/8/005.jpg',
                '../../images/projects/8/006.jpg',
                '../../images/projects/8/007.jpg',
                '../../images/projects/8/008.jpg',
                '../../images/projects/8/009.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Year End Gift',
                  type : 'Branding and Design',
                  cover: '../../images/projects/8/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Year End Gift',
                  type : 'Branding and Design',
                  cover: '../../images/projects/8/cover.jpg',
                }]
          },
          {
              id: 9,
              slug: 'exxaro',
              name: 'Exxaro',
              description: "<p>Exxaro, South Africa's largest producer of coal and coal products recently went through a brand refresh. With this came a refresh of their online and video communication. The Kinetic was briefed to align the art direction across digital platforms and to update and modernise all Exxaro's digital communication.</p>",
              thumb: '../../images/projects/9/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/9/021.jpg',
                '../../images/projects/9/020.jpg',
                '../../images/projects/9/001.jpg',
                '../../images/projects/9/002.jpg',
                '../../images/projects/9/003.jpg',
                '../../images/projects/9/004.jpg',
                '../../images/projects/9/005.jpg',
                '../../images/projects/9/006.jpg',
                '../../images/projects/9/007.jpg',
                '../../images/projects/9/008.jpg',
                '../../images/projects/9/009.jpg',
                '../../images/projects/9/010.jpg',
                '../../images/projects/9/011.jpg',
                '../../images/projects/9/012.jpg',
                '../../images/projects/9/013.jpg',
                '../../images/projects/9/014.jpg',
                '../../images/projects/9/015.jpg',
                '../../images/projects/9/016.jpg',
                '../../images/projects/9/017.jpg',
                '../../images/projects/9/018.jpg',
                '../../images/projects/9/019.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Exxaro',
                  type : 'Corporate and Digital',
                  cover: '../../images/projects/9/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Exxaro',
                  type : 'Corporate and Digital',
                  cover: '../../images/projects/9/cover.jpg',
                }]
          },
          {
              id: 10,
              slug: 'familiar',
              name: 'Familiar',
              description: "<p>A design series inspired by the magic of familiar spirits and other legends connecting a person's soul to an animal. Each print embodies a creature of magical origin or connotation.</p>",
              thumb: '../../images/projects/10/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/10/001.jpg',
                '../../images/projects/10/002.jpg',
                '../../images/projects/10/003.jpg',
                '../../images/projects/10/004.jpg',
                '../../images/projects/10/005.jpg',
                '../../images/projects/10/006.jpg',
                '../../images/projects/10/007.jpg',
                '../../images/projects/10/008.jpg',
                '../../images/projects/10/009.jpg',
                '../../images/projects/10/010.jpg',
                '../../images/projects/10/011.jpg',
                '../../images/projects/10/012.jpg',
                '../../images/projects/10/013.jpg',
                '../../images/projects/10/014.jpg',
                '../../images/projects/10/015.jpg',
                '../../images/projects/10/016.jpg',
                '../../images/projects/10/017.jpg',
                '../../images/projects/10/018.jpg',
                '../../images/projects/10/019.jpg',
                '../../images/projects/10/020.jpg',
                '../../images/projects/10/021.jpg',
                '../../images/projects/10/022.jpg',
                '../../images/projects/10/023.jpg',
                '../../images/projects/10/024.jpg',
                '../../images/projects/10/025.jpg',
                '../../images/projects/10/026.jpg',
                '../../images/projects/10/027.jpg',
                '../../images/projects/10/028.jpg',
                '../../images/projects/10/029.jpg',
                '../../images/projects/10/030.jpg',
                '../../images/projects/10/031.jpg',
                '../../images/projects/10/032.jpg',
                '../../images/projects/10/033.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Familiar',
                  type : 'Illustration',
                  cover: '../../images/projects/10/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Familiar',
                  type : 'Illustration',
                  cover: '../../images/projects/10/cover.jpg',
                }]
          },
          {
              id: 11,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: '../../images/projects/11/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 12,
              slug: 'heard-on-the-streets',
              name: 'HOTS',
              description: "<p>Description needed.</p>",
              thumb: '../../images/projects/12/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/12/001.jpg',
                '../../images/projects/12/002.jpg',
                '../../images/projects/12/003.jpg',
                '../../images/projects/12/004.jpg',
                '../../images/projects/12/005.jpg',
                '../../images/projects/12/006.jpg',
                '../../images/projects/12/007.jpg',
                '../../images/projects/12/008.jpg',
                '../../images/projects/12/009.jpg',
                '../../images/projects/12/010.jpg',
                '../../images/projects/12/011.jpg',
                '../../images/projects/12/013.jpg',
                '../../images/projects/12/014.jpg',
                '../../images/projects/12/015.jpg',
                '../../images/projects/12/016.jpg',
                '../../images/projects/12/017.jpg',
                '../../images/projects/12/018.jpg',
                '../../images/projects/12/019.jpg',
                '../../images/projects/12/020.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'HOTS',
                  type : 'Heard On The Streets Promo',
                  cover: '../../images/projects/12/cover.jpg',
                },
                {
                  id : 2,
                  title : 'HOTS',
                  type : 'Heard On The Streets Promo',
                  cover: '../../images/projects/12/cover.jpg',
                }]
          },
          {
              id: 13,
              slug: 'i-am',
              name: 'I AM',
              description: "<p>A branding and photography project for a South African fashion label.</p>",
              thumb: '../../images/projects/13/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/13/001.jpg',
                '../../images/projects/13/002.jpg',
                '../../images/projects/13/003.jpg',
                '../../images/projects/13/004.jpg',
                '../../images/projects/13/005.jpg',
                '../../images/projects/13/006.jpg',
                '../../images/projects/13/007.jpg',
                '../../images/projects/13/008.jpg',
                '../../images/projects/13/009.jpg',
                '../../images/projects/13/010.jpg',
                '../../images/projects/13/011.jpg',
                '../../images/projects/13/012.jpg',
                '../../images/projects/13/013.png',
                '../../images/projects/13/014.jpg',
                '../../images/projects/13/015.jpg',
                '../../images/projects/13/016.jpg',
                '../../images/projects/13/017.jpg',
                '../../images/projects/13/018.jpg',
                '../../images/projects/13/019.jpg',
                '../../images/projects/13/020.jpg',
                '../../images/projects/13/021.jpg',
                '../../images/projects/13/022.jpg',
                '../../images/projects/13/023.jpg',
                '../../images/projects/13/024.jpg',
                '../../images/projects/13/025.jpg',
                '../../images/projects/13/026.jpg',
                '../../images/projects/13/027.jpg',
                '../../images/projects/13/028.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'I AM',
                  type : 'Branding and Design',
                  cover: '../../images/projects/13/cover.jpg',
                },
                {
                  id : 2,
                  title : 'I AM',
                  type : 'Branding and Design',
                  cover: '../../images/projects/13/cover.jpg',
                }]
          },
          {
              id: 14,
              slug: 'joy-of-jazz',
              name: 'Joy Of Jazz',
              description: "<p>Joy of Jazz 2014 artist line-up</p>",
              thumb: '../../images/projects/14/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/14/001.jpg',
                '../../images/projects/14/002.jpg',
                '../../images/projects/14/003.jpg',
                '../../images/projects/14/004.jpg',
                '../../images/projects/14/005.jpg',
                '../../images/projects/14/006.jpg',
                '../../images/projects/14/007.jpg',
                '../../images/projects/14/008.jpg',
                '../../images/projects/14/009.jpg',
                '../../images/projects/14/010.jpg',
                '../../images/projects/14/011.jpg',
                '../../images/projects/14/012.jpg',
                '../../images/projects/14/013.jpg',
                '../../images/projects/14/014.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Joy Of Jazz',
                  type : 'Show Package 1',
                  cover: '../../images/projects/14/001.jpg',
                },
                {
                  id : 2,
                  title : 'Joy Of Jazz',
                  type : 'Show Package 3',
                  cover: '../../images/projects/14/001.jpg',
                }]
          },
          {
              id: 15,
              slug: 'kfc-big-bash-league',
              name: 'KFC Big Bash League',
              description: "<p>T20 games are electrifying; the atmosphere is filled with excitement, action and celebration. Teams go face to face with big hits and epic catches in this fast paced game. It’s a concentration of the most exciting elements of cricket. We wanted to capture these high energy moments and create an equally energetic treatment to reflect this. These moments are heightened with cel animated ‘light storm’ like electric illustrations to express how big the catches, wickets and hits really are. It’s not just cricket it’s High Voltage Cricket.</p>",
              thumb: '../../images/projects/15/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/15/001.jpg',
                '../../images/projects/15/002.jpg',
                '../../images/projects/15/003.jpg',
                '../../images/projects/15/004.jpg',
                '../../images/projects/15/005.jpg',
                '../../images/projects/15/006.jpg',
                '../../images/projects/15/007.jpg',
                '../../images/projects/15/008.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'KFC Big Bash',
                  type : 'Promo Concept',
                  cover: '../../images/projects/15/cover.jpg',
                },
                {
                  id : 2,
                  title : 'KFC Big Bash',
                  type : 'Promo Concept',
                  cover: '../../images/projects/15/cover.jpg',
                }]
          },
          {
              id: 16,
              slug: 'lamande',
              name: "L'Amande De Macaron",
              description: "<p>A corporate identity for a sophisticated, modern and tasty brand. The recipe of the brand lies in bold colours and photographed textures combined with sleek, simple design that intensifies the taste for this handcrafted experience. L'Amande is not colour specific; it blends with each flavour creating an array of flavours and textures to work with and be inspired by. The hand drawn logo combined with crisp, slick design captures the experience of a macaron with its crisp outer shell and gooey filling. L'Amande de Macaron is not just about baking, but about all the flavours of life and the branding serves as a foretaste for this. L'Amande is all for the melting, immaculate, tasty almond perfection that is a Macaron.</p>",
              thumb: '../../images/projects/16/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/16/001.jpg',
                '../../images/projects/16/002.jpg',
                '../../images/projects/16/003.jpg',
                '../../images/projects/16/004.jpg',
                '../../images/projects/16/005.jpg',
                '../../images/projects/16/006.jpg',
                '../../images/projects/16/007.jpg',
                '../../images/projects/16/008.jpg',
                '../../images/projects/16/009.jpg',
                '../../images/projects/16/010.jpg',
                '../../images/projects/16/011.jpg',
                '../../images/projects/16/012.jpg',
                '../../images/projects/16/013.jpg',
                '../../images/projects/16/014.jpg',
                '../../images/projects/16/015.jpg',
                '../../images/projects/16/016.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "L'Amande",
                  type : 'Branding and Design',
                  cover: '../../images/projects/16/cover.jpg',
                },
                {
                  id : 2,
                  title : "L'Amande",
                  type : 'Branding and Design',
                  cover: '../../images/projects/16/cover.jpg',
                }]
          },
          {
              id: 17,
              slug: 'm-net-channel-branding',
              name: 'M-Net Channel Branding',
              description: "<p>We were invited to take part in a treatment process for the update of South Africa's premier digital satellite TV channel, M-Net. Our main working concept was to bring the brand back to a point where the channels focus was its content. Users know and understand that the channel broadcasts premier television content, and we wanted to focus on that fact. The channel should amplify the content, and through that, itself.</p><p>The channel pay-off line was tweaked to 'Your magic begins here', and this was initiated by the fact that the best content is hosted on the M-Net and is the first channel in the satellite bouquet. This tied into the historic usage of the word 'magic' in M-Net's brand communication and how creating television magic has become synonymous with the viewing public in South Africa.</p><p>Utilising 2 simple and sleek treatment options, we focused on highlighting the world class content and presenting the viewer with a channel they can immediately recognise as M-Net.</p>",
              thumb: '../../images/projects/17/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/17/001.jpg',
                '../../images/projects/17/002.jpg',
                '../../images/projects/17/003.jpg',
                '../../images/projects/17/004.jpg',
                '../../images/projects/17/005.jpg',
                '../../images/projects/17/006.jpg',
                '../../images/projects/17/007.jpg',
                '../../images/projects/17/008.jpg',
                '../../images/projects/17/009.jpg',
                '../../images/projects/17/010.jpg',
                '../../images/projects/17/011.jpg',
                '../../images/projects/17/012.jpg',
                '../../images/projects/17/013.jpg',
                '../../images/projects/17/014.jpg',
                '../../images/projects/17/015.jpg',
                '../../images/projects/17/016.jpg',
                '../../images/projects/17/017.jpg',
                '../../images/projects/17/018.jpg',
                '../../images/projects/17/019.jpg',
                '../../images/projects/17/020.jpg',
                '../../images/projects/17/021.jpg',
                '../../images/projects/17/022.jpg',
                '../../images/projects/17/023.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'M-Net',
                  type : 'Channel Rebrand',
                  cover: '../../images/projects/17/cover.jpg',
                },
                {
                  id : 2,
                  title : 'M-Net',
                  type : 'Channel Rebrand',
                  cover: '../../images/projects/17/cover.jpg',
                }]
          },
          {
              id: 18,
              slug: 'mtv-my-mix-tape',
              name: 'MTV My Mix Tape',
              description: "<p>A short title sequence and strap for a countdown show on MTV Base that showcases pop and dance music from around Africa.</p>",
              thumb: '../../images/projects/18/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/18/001.jpg',
                '../../images/projects/18/002.jpg',
                '../../images/projects/18/003.jpg',
                '../../images/projects/18/004.jpg',
                '../../images/projects/18/006.jpg',
                '../../images/projects/18/007.jpg',
                '../../images/projects/18/008.jpg',
                '../../images/projects/18/009.jpg',
                '../../images/projects/18/010.jpg',
                '../../images/projects/18/011.jpg',
                '../../images/projects/18/012.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'MTV My Mix Tape',
                  type : 'Show Package 1',
                  cover: '../../images/projects/18/007.jpg',
                },
                {
                  id : 2,
                  title : 'MTV My Mix Tape',
                  type : 'Show Package 3',
                  cover: '../../images/projects/18/007.jpg',
                }]
          },
          {
              id: 19,
              slug: 'mtv-this-is-how-we-bring-it',
              name: 'MTV This Is How We Bring It',
              description: "<p>A short promo The Kinetic did for MTV Networks Africa. Package included top and tail graphics, straps and other small elements.</p>",
              thumb: '../../images/projects/19/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/19/001.jpg',
                '../../images/projects/19/002.jpg',
                '../../images/projects/19/003.jpg',
                '../../images/projects/19/004.jpg',
                '../../images/projects/19/006.jpg',
                '../../images/projects/19/007.jpg',
                '../../images/projects/19/008.jpg',
                '../../images/projects/19/009.jpg',
                '../../images/projects/19/010.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'MTV This Is How We Bring It',
                  type : 'Show Package 1',
                  cover: '../../images/projects/19/004.jpg',
                },
                {
                  id : 2,
                  title : 'MTV This Is How We Bring It',
                  type : 'Show Package 3',
                  cover: '../../images/projects/19/004.jpg',
                }]
          },
          {
              id: 20,
              slug: 'nikki-se-nee',
              name: 'Nikki Sê Nee',
              description: "<p>Description needed.</p>",
              thumb: '../../images/projects/20/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/20/001.jpg',
                '../../images/projects/20/007.jpg',
                '../../images/projects/20/010.jpg',
                '../../images/projects/20/011.jpg',
                '../../images/projects/20/002.jpg',
                '../../images/projects/20/003.jpg',
                '../../images/projects/20/004.jpg',
                '../../images/projects/20/006.jpg',
                '../../images/projects/20/008.jpg',
                '../../images/projects/20/009.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Nikki Sê Nee',
                  type : 'Show Package',
                  cover: '../../images/projects/20/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Nikki Sê Nee',
                  type : 'Show Package',
                  cover: '../../images/projects/20/cover.jpg',
                }]
          },
          {
              id: 21,
              slug: 'nomad',
              name: 'Nomad',
              description: "<p>Description needed.</p>",
              thumb: '../../images/projects/21/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/21/001.jpg',
                '../../images/projects/21/002.jpg',
                '../../images/projects/21/003.jpg',
                '../../images/projects/21/004.jpg',
                '../../images/projects/21/005.jpg',
                '../../images/projects/21/006.jpg',
                '../../images/projects/21/007.jpg',
                '../../images/projects/21/008.jpg',
                '../../images/projects/21/009.jpg',
                '../../images/projects/21/010.jpg',
                '../../images/projects/21/011.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Nomad',
                  type : 'Show Package 1',
                  cover: '../../images/projects/21/006.jpg',
                },
                {
                  id : 2,
                  title : 'Nomad',
                  type : 'Show Package 3',
                  cover: '../../images/projects/21/006.jpg',
                }]
          },
          {
              id: 22,
              slug: 'pica-awards',
              name: 'PiCA Awards',
              description: "<p>The Pica Awards ceremony is anannual event showcasing and recognising excellence in magazine publishing. Thispiece explores the lesser seen and often overlooked world of paper, printing and layout. The package included a main awards sequence, category winners and various other smaller elements.</p>",
              thumb: '../../images/projects/22/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/22/001.jpg',
                '../../images/projects/22/002.jpg',
                '../../images/projects/22/003.jpg',
                '../../images/projects/22/004.jpg',
                '../../images/projects/22/005.jpg',
                '../../images/projects/22/006.jpg',
                '../../images/projects/22/007.jpg',
                '../../images/projects/22/008.jpg',
                '../../images/projects/22/009.jpg',
                '../../images/projects/22/010.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'PiCA Awards',
                  type : 'Awards AV and Elements',
                  cover: '../../images/projects/22/cover.jpg',
                },
                {
                  id : 2,
                  title : 'PiCA Awards',
                  type : 'Awards AV and Elements',
                  cover: '../../images/projects/22/cover.jpg',
                }]
          },
          {
              id: 23,
              slug: 'reggies',
              name: 'Reggies',
              description: "<p>A 15 second competition promo for a South African toy store.The brief was as simple as to make the viewer want to lick the screen and want to be on holiday. Short and 'sweet'.</p>",
              thumb: '../../images/projects/23/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/23/001.jpg',
                '../../images/projects/23/002.jpg',
                '../../images/projects/23/003.jpg',
                '../../images/projects/23/004.jpg',
                '../../images/projects/23/005.jpg',
                '../../images/projects/23/006.jpg',
                '../../images/projects/23/007.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Reggies',
                  type : 'TVC',
                  cover: '../../images/projects/23/cover.jpg',
                },
                {
                  id : 2,
                  title : 'Reggies',
                  type : 'TVC',
                  cover: '../../images/projects/23/cover.jpg',
                }]
          },
          {
              id: 24,
              slug: 'safta-awards',
              name: 'SAFTA Awards',
              description: "<p>The Kinetic designed and executed an original concept for the 2013 South African Film and Video Awards' show graphics and title package, presented live from Gallagher estate, Johannesburg and broadcast exclusively by SABC 3.</p><p>The purpose was to visually align the branding of the night with the objectives of the SAFTA awards itself, where an event unites and celebrates the quality and excellence of South African Film and Television – honouring and promoting the creativity of the writers, directors and technical crews.</p><p>The piece had to match the prestige and glamour of the SAFTAs and we drew heavily on the shape of the trophy, which has become iconic within the industry. The fractured Statuette, becoming whole as the pieces combine, draws a parallel to the industry where great works are forged, often under immense pressure, becoming greater than the sum of their parts.</p>",
              thumb: '../../images/projects/24/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/24/001.jpg',
                '../../images/projects/24/002.jpg',
                '../../images/projects/24/003.jpg',
                '../../images/projects/24/004.jpg',
                '../../images/projects/24/010.jpg',
                '../../images/projects/24/005.jpg',
                '../../images/projects/24/006.jpg',
                '../../images/projects/24/007.jpg',
                '../../images/projects/24/008.jpg',
                '../../images/projects/24/009.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'SAFTA Awards',
                  type : 'Show Package',
                  cover: '../../images/projects/24/cover.jpg',
                },
                {
                  id : 2,
                  title : 'SAFTA Awards',
                  type : 'Show Package',
                  cover: '../../images/projects/24/cover.jpg',
                }]
          },
          {
              id: 25,
              slug: 'saia-awards-2011',
              name: "SAIA Awards 2011",
              description: "<p>A series of AVs The Kinetic produced for the South African Institute of Architects annual award ceremony held in Johannesburg. The Concept centered on the processes architects employ in the creation and design of buildings. The video features an edit of all the elements produced for the ceremony.</p>",
              thumb: '../../images/projects/25/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/25/001.jpg',
                '../../images/projects/25/002.jpg',
                '../../images/projects/25/003.jpg',
                '../../images/projects/25/004.jpg',
                '../../images/projects/25/005.jpg',
                '../../images/projects/25/006.jpg',
                '../../images/projects/25/007.jpg',
                '../../images/projects/25/008.jpg',
                '../../images/projects/25/009.jpg',
                '../../images/projects/25/010.jpg',
                '../../images/projects/25/011.jpg',
                '../../images/projects/25/012.jpg',
                '../../images/projects/25/013.jpg',
                '../../images/projects/25/014.jpg',
                '../../images/projects/25/015.jpg',
                '../../images/projects/25/016.jpg',
                '../../images/projects/25/017.jpg',
                '../../images/projects/25/018.jpg',
                '../../images/projects/25/019.jpg',
                '../../images/projects/25/020.jpg',
                '../../images/projects/25/021.jpg',
                '../../images/projects/25/022.jpg',
                '../../images/projects/25/023.jpg',
                '../../images/projects/25/024.jpg',
                '../../images/projects/25/025.jpg',
                '../../images/projects/25/026.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "SAIA Awards 2011",
                  type : 'Awards AV and Elements',
                  cover: '../../images/projects/25/cover.jpg',
                },
                {
                  id : 2,
                  title : "SAIA Awards 2011",
                  type : 'Awards AV and Elements',
                  cover: '../../images/projects/25/cover.jpg',
                }]
          },
          {
              id: 26,
              slug: 'SAIA-Awards-2013',
              name: "SAIA Awards 2013",
              description: "<p>The Afrisam SAIA Awards aim to recognise outstanding achievement in sustainable architecture. To compliment their vision, The Kinetic was asked to create a series of videos for online marketing as well as a series of event specific AVs to reveal the winner's in each category. We developed a stop frame approach to further expand on the visual style developed in previous years. The concept explores the creative process of architecture through an abstracted examination of their tools.</p>",
              thumb: '../../images/projects/26/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/26/001.jpg',
                '../../images/projects/26/002.jpg',
                '../../images/projects/26/003.jpg',
                '../../images/projects/26/004.jpg',
                '../../images/projects/26/005.jpg',
                '../../images/projects/26/006.jpg',
                '../../images/projects/26/007.jpg',
                '../../images/projects/26/008.jpg',
                '../../images/projects/26/009.jpg',
                '../../images/projects/26/010.jpg',
                '../../images/projects/26/011.jpg',
                '../../images/projects/26/012.jpg',
                '../../images/projects/26/013.jpg',
                '../../images/projects/26/014.jpg',
                '../../images/projects/26/015.jpg',
                '../../images/projects/26/016.jpg',
                '../../images/projects/26/017.jpg',
                '../../images/projects/26/018.jpg',
                '../../images/projects/26/019.jpg',
                '../../images/projects/26/020.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "SAIA Awards 2013",
                  type : 'Awards AV and Elements',
                  cover: '../../images/projects/26/cover.jpg',
                },
                {
                  id : 2,
                  title : "SAIA Awards 2013",
                  type : 'Awards AV and Elements',
                  cover: '../../images/projects/26/cover.jpg',
                }]
          },
          {
              id: 27,
              slug: 'str-crd',
              name: "STR.CRD",
              description: "<p>Description yet to come.</p>",
              thumb: '../../images/projects/27/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/27/001.jpg',
                '../../images/projects/27/002.jpg',
                '../../images/projects/27/003.jpg',
                '../../images/projects/27/004.jpg',
                '../../images/projects/27/005.jpg',
                '../../images/projects/27/006.jpg',
                '../../images/projects/27/007.jpg',
                '../../images/projects/27/008.jpg',
                '../../images/projects/27/009.jpg',
                '../../images/projects/27/010.jpg',
                '../../images/projects/27/011.jpg',
                '../../images/projects/27/012.jpg',
                '../../images/projects/27/013.jpg',
                '../../images/projects/27/014.jpg',
                '../../images/projects/27/015.jpg',
                '../../images/projects/27/016.jpg',
                '../../images/projects/27/017.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "STR.CRD",
                  type : 'Show Package 1',
                  cover: '../../images/projects/27/003.jpg',
                },
                {
                  id : 2,
                  title : "STR.CRD",
                  type : 'Show Package 3',
                  cover: '../../images/projects/27/003.jpg',
                }]
          },
          {
              id: 28,
              slug: 'business-cards',
              name: "Business Cards",
              description: "<p>Description to come</p>",
              thumb: '../../images/projects/28/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/28/001.jpg',
                '../../images/projects/28/002.jpg',
                '../../images/projects/28/003.jpg',
                '../../images/projects/28/004.jpg',
                '../../images/projects/28/005.jpg',
                '../../images/projects/28/006.jpg',
                '../../images/projects/28/007.jpg',
                '../../images/projects/28/008.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "Business Cards",
                  type : 'The Kinetic Branding',
                  cover: '../../images/projects/28/cover.jpg',
                },
                {
                  id : 2,
                  title : "Business Cards",
                  type : 'The Kinetic Branding',
                  cover: '../../images/projects/28/cover.jpg',
                }]
          },
          {
              id: 29,
              slug: 'laws-of-motion',
              name: "Laws of Motion",
              description: "<p>The concept behind THREE explores one of the most important theories that formed the basis for our understanding of the natural world.</p><p>The series visually interprets Newton's laws of motion through the relationship between various forces and dynamic bodies set in every day locations.</p>",
              thumb: '../../images/projects/29/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/29/001.jpg',
                '../../images/projects/29/002.jpg',
                '../../images/projects/29/003.jpg',
                '../../images/projects/29/004.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "Laws of Motion",
                  type : 'Proof of Concept Motion Design',
                  cover: '../../images/projects/29/cover.jpg',
                },
                {
                  id : 2,
                  title : "Laws of Motion",
                  type : 'Proof of Concept Motion Design',
                  cover: '../../images/projects/29/cover.jpg',
                }]
          },
          {
              id: 30,
              slug: 'uj',
              name: "UJ",
              description: "<p>Following the success of their 2010 recruitment run, the University of Johannesburg wanted to expand their communications to broadcast. The Kinetic created this 30sec TVC based on an original artwork made by Am I Collective for UJ. The animation involved the re-creation of dozens 2D illustrated elements into 3D models to create the rich and fantastical world of UJ where you can 'be anything you want you be'.</p>",
              thumb: '../../images/projects/30/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/30/001.jpg',
                '../../images/projects/30/002.jpg',
                '../../images/projects/30/003.jpg',
                '../../images/projects/30/004.jpg',
                '../../images/projects/30/005.jpg',
                '../../images/projects/30/006.jpg',
                '../../images/projects/30/007.jpg',
                '../../images/projects/30/008.jpg',
                '../../images/projects/30/009.jpg',
                '../../images/projects/30/010.jpg',
                '../../images/projects/30/011.jpg',
                '../../images/projects/30/012.jpg',
                '../../images/projects/30/013.jpg',
                '../../images/projects/30/014.jpg',
                '../../images/projects/30/015.jpg',
                '../../images/projects/30/016.jpg',
                '../../images/projects/30/017.jpg',
                '../../images/projects/30/018.jpg',
                '../../images/projects/30/019.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "UJ",
                  type : 'TVC',
                  cover: '../../images/projects/30/cover.jpg',
                },
                {
                  id : 2,
                  title : "UJ",
                  type : 'TVC',
                  cover: '../../images/projects/30/cover.jpg',
                }]
          },
          {
              id: 31,
              slug: 'valo-pictures',
              name: "VALO Pictures",
              description: "<p>A branding project for our friends at Valo. As the word 'Valo' means light, the concept was as simple as to communicate this meaning, and that this film production company concentrates on creating emotive and beautiful film making.</p>",
              thumb: '../../images/projects/31/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/31/001.jpg',
                '../../images/projects/31/002.jpg',
                '../../images/projects/31/003.jpg',
                '../../images/projects/31/004.jpg',
                '../../images/projects/31/005.jpg',
                '../../images/projects/31/006.jpg',
                '../../images/projects/31/007.jpg',
                '../../images/projects/31/008.jpg',
                '../../images/projects/31/009.jpg',
                '../../images/projects/31/010.jpg',
                '../../images/projects/31/011.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "VALO Pictures",
                  type : 'Branding and Design',
                  cover: '../../images/projects/31/cover.jpg',
                },
                {
                  id : 2,
                  title : "VALO Pictures",
                  type : 'Branding and Design',
                  cover: '../../images/projects/31/cover.jpg',
                }]
          },
          {
              id: 32,
              slug: 'vuzu-amp',
              name: "Vuzu Amp",
              description: "<p>A short promo for Vuzu Amp's 'Month of love'.</p>",
              thumb: '../../images/projects/32/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/32/001.jpg',
                '../../images/projects/32/002.jpg',
                '../../images/projects/32/003.jpg',
                '../../images/projects/32/004.jpg',
                '../../images/projects/32/005.jpg',
                '../../images/projects/32/006.jpg',
                '../../images/projects/32/007.jpg',
                '../../images/projects/32/008.jpg',
                '../../images/projects/32/009.jpg',
                '../../images/projects/32/010.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : "Vuzu Amp",
                  type : 'Promo',
                  cover: '../../images/projects/32/cover.jpg',
                },
                {
                  id : 2,
                  title : "Vuzu Amp",
                  type : 'Promo',
                  cover: '../../images/projects/32/cover.jpg',
                }]
          }];
          return {
              list: function(){
                  return projects;
              },
              find: function(id){
                  return _.find(projects, function(project){
                    return project.id == id;
                  });
              }
          };
          /* jshint ignore:end */
        });

  })(); 