(function () { 

	'use strict';

	/**
	 * @ngdoc function
	 * @name kinetixApp.controller:ProjectService
	 * @description
	 * # ProjectService
	 * Service of the projects for kinetixApp
	 */
	angular.module('kinetixApp')
	  .service('ProjectService', function(){
         /* jshint ignore:start */
          var projects = [{
              id: 1,
              slug: 'anglo-american-3d-annual-communications-summit',
              name: 'Anglo American 3d Annual Communications Summit',
              description: "<p>For the last 2 years Anglo American has held a global conference to bring together the marketing heads of all the wings in the organisation, aiming to consolidate and strategise a holistic strategy for the year to come. This year Cape Town was selected as the Venue and The Kinetic was brought on board to produce all the digital assets for the conference. Aiming to modernize the company, one of the key areas was the incorporation of an Ipad app rather than having a traditional printed conference program.</p> <p>Further more the delivery included a website for the conference, invitational emails sent out bi-weekly which each included a 1 minute video trailer to the event. The videos’ narratives were linked and built from one to the next. The culmination video including all the teasers along with a resolution message was screened at the conference opening along with on-screen content loops which ran throughout the conference.</p>",
              thumb: '../../images/projects/1/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/1/001.jpg',
                '../../images/projects/1/002.jpg',
                '../../images/projects/1/003.jpg',
                '../../images/projects/1/004.jpg',
                '../../images/projects/1/005.jpg',
                '../../images/projects/1/006.jpg',
                '../../images/projects/1/007.jpg',
                '../../images/projects/1/008.jpg',
                '../../images/projects/1/009.jpg',
                '../../images/projects/1/010.jpg',
                '../../images/projects/1/011.jpg',
                '../../images/projects/1/012.jpg',
                '../../images/projects/1/013.jpg',
                '../../images/projects/1/014.jpg',
                '../../images/projects/1/015.jpg',
                '../../images/projects/1/016.jpg',
                '../../images/projects/1/017.jpg',
                '../../images/projects/1/018.jpg',
                '../../images/projects/1/019.jpg',
                '../../images/projects/1/020.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Anglo American Comms Summit',
                  type : 'Show Package 1',
                  cover: '../../images/projects/1/018.jpg',
                  source: '119763015'
                },
                {
                  id : 2,
                  title : 'Anglo American Comms Summit',
                  type : 'Show Package 2',
                  cover: '../../images/video-cover.jpg',
                  source: '60631991'
                },
                {
                  id : 3,
                  title : 'Anglo American Comms Summit',
                  type : 'Show Package 3',
                  cover: '../../images/video-cover.jpg',
                  source: '60631991'
                }]
          },
          {
              id: 2,
              slug: 'armour',
              name: 'Armour',
              description: "<p>A visual identity inspired by bikes, beer and general badassness. The handmade feel of the Armour brand celebrates those who brew the beer they drink and build the bikes they ride.</p>",
              thumb: '../../images/projects/2/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/2/001.jpg',
                '../../images/projects/2/002.jpg',
                '../../images/projects/2/003.jpg',
                '../../images/projects/2/004.jpg',
                '../../images/projects/2/005.jpg',
                '../../images/projects/2/006.jpg',
                '../../images/projects/2/007.jpg',
                '../../images/projects/2/008.jpg',
                '../../images/projects/2/010.jpg',
                '../../images/projects/2/011.jpg',
                '../../images/projects/2/012.jpg',
                '../../images/projects/2/013.jpg',
                '../../images/projects/2/014.jpg',
                '../../images/projects/2/015.jpg',
                '../../images/projects/2/016.gif',
                '../../images/projects/2/017.jpg',
                '../../images/projects/2/018.jpg',
                '../../images/projects/2/019.gif',
                '../../images/projects/2/020.jpg',
                '../../images/projects/2/009.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Armour',
                  type : 'Show Package 1',
                  cover: '../../images/projects/2/011.jpg',
                },
                {
                  id : 2,
                  title : 'Armour',
                  type : 'Show Package 3',
                  cover: '../../images/projects/2/011.jpg',
                }]
          },
          {
              id: 3,
              slug: 'basa-awards-av',
              name: 'BASA Awards AV',
              description: "<p>The Business of the Arts South Africa is a non-profit organization that seeks to partner big business with local artists. An annual awards ceremony gives recognition to companies that have made a substantial and sustainable contribution to the arts, previous winners of this coveted award include Cell C, Deloitte and Absa.</p><p>It is a worthy cause and one that has over the years ensured a thriving culture of corporately funded artistic expression, adding to the already substantial body of world renowned work produced by South African artists. When we were asked to create a series of video pieces for the award ceremony, we were very excited to add our name to the long list of companies that support and believe in local art.</p>",
              thumb: '../../images/projects/3/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/3/001.jpg',
                '../../images/projects/3/002.jpg',
                '../../images/projects/3/003.jpg',
                '../../images/projects/3/004.jpg',
                '../../images/projects/3/005.jpg',
                '../../images/projects/3/006.jpg',
                '../../images/projects/3/007.jpg',
                '../../images/projects/3/008.jpg',
                '../../images/projects/3/009.jpg',
                '../../images/projects/3/010.jpg',
                '../../images/projects/3/011.jpg',
                '../../images/projects/3/012.jpg',
                '../../images/projects/3/013.jpg',
                '../../images/projects/3/014.jpg',
                '../../images/projects/3/015.jpg'
              ],
              videos : [
                {
                  id : 1,
                  title : 'BASA Awards AV',
                  type : 'Show Package 1',
                  cover: '../../images/projects/3/010.jpg',
                },
                {
                  id : 2,
                  title : 'BASA Awards AV',
                  type : 'Show Package 3',
                  cover: '../../images/projects/3/010.jpg',
                }]
          },
          {
              id: 4,
              slug: 'samsung-amaze-africa',
              name: 'Samsung Amaze Africa',
              description: "<p>The Kinetic was approached by Breinstorm Brand Architects to create a series of AV projection elements for the Samsung Amaze Africa fashion show at the Pretoria City Hall. Each fashion designer was paired with an accessory designer and together they designed a line of fashion inspired by a specific type of fauna and flora found at the National Museum of Natural History across the road from where the show was held.<p></p>The AV elements also had to stem from this Natural object inspiration and were key in the creation of the lighting and overall show design.</p>",
              thumb: '../../images/projects/4/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/4/001.jpg',
                '../../images/projects/4/002.jpg',
                '../../images/projects/4/003.jpg',
                '../../images/projects/4/004.jpg',
                '../../images/projects/4/005.jpg',
                '../../images/projects/4/006.jpg',
                '../../images/projects/4/007.jpg',
                '../../images/projects/4/008.jpg',
                '../../images/projects/4/009.jpg',
                '../../images/projects/4/010.jpg',
                '../../images/projects/4/011.jpg',
                '../../images/projects/4/012.jpg',
                '../../images/projects/4/013.jpg',
                '../../images/projects/4/014.jpg',
                '../../images/projects/4/015.jpg',
                '../../images/projects/4/016.jpg',
                '../../images/projects/4/017.jpg',
                '../../images/projects/4/018.jpg',
                '../../images/projects/4/019.jpg',
                '../../images/projects/4/020.jpg',
                '../../images/projects/4/021.jpg',
                '../../images/projects/4/022.jpg',
                '../../images/projects/4/023.jpg',
                '../../images/projects/4/024.jpg',
                '../../images/projects/4/025.jpg',
                '../../images/projects/4/026.jpg',
                '../../images/projects/4/027.jpg',
                '../../images/projects/4/028.jpg',
                '../../images/projects/4/029.jpg',
                '../../images/projects/4/030.jpg',
                '../../images/projects/4/031.jpg',
                '../../images/projects/4/032.jpg',
                '../../images/projects/4/033.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Samsung Amaze Africa',
                  type : 'Show Package 1',
                  cover: '../../images/projects/4/003.jpg',
                },
                {
                  id : 2,
                  title : 'Samsung Amaze Africa',
                  type : 'Show Package 3',
                  cover: '../../images/projects/4/003.jpg',
                }]
          },
          {
              id: 5,
              slug: 'cennergi',
              name: 'Cennergi',
              description: "<p>HKLM commissioned The Kinetic to produce a video for the launch of South Africa's new independant energy provider's brand reveal function. The aim being to showcase the brand’s vibrancy and to leave attendees with a deeper understanding and lasting excitement for Cennergi.</p><p>We also created a series of sponsor boards to coincide with the launch on broadcast television.</p>",
              thumb: '../../images/projects/5/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/5/001.jpg',
                '../../images/projects/5/002.jpg',
                '../../images/projects/5/003.jpg',
                '../../images/projects/5/004.jpg',
                '../../images/projects/5/005.jpg',
                '../../images/projects/5/006.jpg',
                '../../images/projects/5/007.jpg',
                '../../images/projects/5/008.jpg',
                '../../images/projects/5/009.jpg',
                '../../images/projects/5/010.jpg',
                '../../images/projects/5/011.jpg'
              ],
              videos : [
                {
                  id : 1,
                  title : 'Cennergi',
                  type : 'Show Package 1',
                  cover: '../../images/projects/5/005.jpg',
                },
                {
                  id : 2,
                  title : 'Cennergi',
                  type : 'Show Package 3',
                  cover: '../../images/projects/5/005.jpg',
                }]
          },
          {
              id: 6,
              slug: 'battlecat',
              name: 'Battlecat!',
              description: "<p>Description still to come here</p>",
              thumb: '../../images/projects/6/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/6/1.jpg',
                '../../images/projects/6/2.jpg',
                '../../images/projects/6/3.jpg',
                '../../images/projects/6/4.jpg'
              ],
              videos : [
                {
                  id : 1,
                  title : 'Battlecat!',
                  type : 'Show Package 1',
                  cover: '../../images/projects/6/1.jpg',
                },
                {
                  id : 2,
                  title : 'Battlecat!',
                  type : 'Show Package 3',
                  cover: '../../images/projects/6/1.jpg',
                }]
          },
          {
              id: 7,
              slug: 'cancel-fashion-collective',
              name: 'Cancel Fashion Collective',
              description: "<p>Cancel is a collective of fashion designers and fashion event organisers, this project shows the brand development, photography and launch video of the Cancel fashion collective brand.</p>",
              thumb: '../../images/projects/7/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/7/001.jpg',
                '../../images/projects/7/002.jpg',
                '../../images/projects/7/003.jpg',
                '../../images/projects/7/004.jpg',
                '../../images/projects/7/005.jpg',
                '../../images/projects/7/006.jpg',
                '../../images/projects/7/007.jpg',
                '../../images/projects/7/008.jpg',
                '../../images/projects/7/009.jpg',
                '../../images/projects/7/010.jpg',
                '../../images/projects/7/011.jpg',
                '../../images/projects/7/012.jpg',
                '../../images/projects/7/013.jpg',
                '../../images/projects/7/014.jpg',
                '../../images/projects/7/015.jpg',
                '../../images/projects/7/016.jpg',
                '../../images/projects/7/017.jpg',
                '../../images/projects/7/018.jpg',
                '../../images/projects/7/019.jpg',
                '../../images/projects/7/020.jpg',
                '../../images/projects/7/021.jpg',
                '../../images/projects/7/022.jpg',
                '../../images/projects/7/023.jpg',
                '../../images/projects/7/024.jpg',
                '../../images/projects/7/025.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Cancel Fashion Collective',
                  type : 'Show Package 1',
                  cover: '../../images/projects/7/018.jpg',
                },
                {
                  id : 2,
                  title : 'Cancel Fashion Collective',
                  type : 'Show Package 3',
                  cover: '../../images/projects/7/018.jpg',
                }]
          },
          {
              id: 8,
              slug: 'end-year-gift-2015',
              name: 'End Year Gift 2015',
              description: "<p>We made some extra special end year gifts in 2015 with the help of Hope On Hopkins in Cape Town, have a look.</p>",
              thumb: '../../images/projects/8/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/8/001.jpg',
                '../../images/projects/8/002.jpg',
                '../../images/projects/8/003.jpg',
                '../../images/projects/8/004.jpg',
                '../../images/projects/8/005.jpg',
                '../../images/projects/8/006.jpg',
                '../../images/projects/8/007.jpg',
                '../../images/projects/8/008.jpg',
                '../../images/projects/8/009.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'End Year Gift 2015',
                  type : 'Show Package 1',
                  cover: '../../images/projects/8/001.jpg',
                },
                {
                  id : 2,
                  title : 'End Year Gift 2015',
                  type : 'Show Package 3',
                  cover: '../../images/projects/8/001.jpg',
                }]
          },
          {
              id: 9,
              slug: 'exxaro-digital',
              name: 'Exxaro Digital',
              description: "<p>Exxaro, South Africa's largest producer of coal and coal products recently went through a brand refresh. With this came a refresh of their online and video communication. The Kinetic was briefed to align the art direction across digital platforms and to update and modernise all Exxaro's digital communication.</p>",
              thumb: '../../images/projects/9/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/9/021.jpg',
                '../../images/projects/9/020.jpg',
                '../../images/projects/9/001.jpg',
                '../../images/projects/9/002.jpg',
                '../../images/projects/9/003.jpg',
                '../../images/projects/9/004.jpg',
                '../../images/projects/9/005.jpg',
                '../../images/projects/9/006.jpg',
                '../../images/projects/9/007.jpg',
                '../../images/projects/9/008.jpg',
                '../../images/projects/9/009.jpg',
                '../../images/projects/9/010.jpg',
                '../../images/projects/9/011.jpg',
                '../../images/projects/9/012.jpg',
                '../../images/projects/9/013.jpg',
                '../../images/projects/9/014.jpg',
                '../../images/projects/9/015.jpg',
                '../../images/projects/9/016.jpg',
                '../../images/projects/9/017.jpg',
                '../../images/projects/9/018.jpg',
                '../../images/projects/9/019.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Exxaro Digital',
                  type : 'Show Package 1',
                  cover: '../../images/projects/9/011.jpg',
                },
                {
                  id : 2,
                  title : 'Exxaro Digital',
                  type : 'Show Package 3',
                  cover: '../../images/projects/9/011.jpg',
                }]
          },
          {
              id: 10,
              slug: 'familiar',
              name: 'Familiar',
              description: "<p>A design series inspired by the magic of familiar spirits and other legends connecting a person's soul to an animal. Each print embodies a creature of magical origin or connotation.</p>",
              thumb: '../../images/projects/10/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/10/001.jpg',
                '../../images/projects/10/002.jpg',
                '../../images/projects/10/003.jpg',
                '../../images/projects/10/004.jpg',
                '../../images/projects/10/005.jpg',
                '../../images/projects/10/006.jpg',
                '../../images/projects/10/007.jpg',
                '../../images/projects/10/008.jpg',
                '../../images/projects/10/009.jpg',
                '../../images/projects/10/010.jpg',
                '../../images/projects/10/011.jpg',
                '../../images/projects/10/012.jpg',
                '../../images/projects/10/013.jpg',
                '../../images/projects/10/014.jpg',
                '../../images/projects/10/015.jpg',
                '../../images/projects/10/016.jpg',
                '../../images/projects/10/017.jpg',
                '../../images/projects/10/018.jpg',
                '../../images/projects/10/019.jpg',
                '../../images/projects/10/020.jpg',
                '../../images/projects/10/021.jpg',
                '../../images/projects/10/022.jpg',
                '../../images/projects/10/023.jpg',
                '../../images/projects/10/024.jpg',
                '../../images/projects/10/025.jpg',
                '../../images/projects/10/026.jpg',
                '../../images/projects/10/027.jpg',
                '../../images/projects/10/028.jpg',
                '../../images/projects/10/029.jpg',
                '../../images/projects/10/030.jpg',
                '../../images/projects/10/031.jpg',
                '../../images/projects/10/032.jpg',
                '../../images/projects/10/033.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Familiar',
                  type : 'Show Package 1',
                  cover: '../../images/projects/10/002.jpg',
                },
                {
                  id : 2,
                  title : 'Familiar',
                  type : 'Show Package 3',
                  cover: '../../images/projects/10/002.jpg',
                }]
          },
          {
              id: 11,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Branding and Promotion of the VUZU Tv show Heard on the Streets, where aspiring young film-makers get a budget to go out and shoot a 2-3min 'CONVO' about what it means to be young in South Africa. The Brief included an On-air promo, the packaging of the CONVO's as well as various online elements.</p>",
              thumb: '../../images/projects/11/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 12,
              slug: 'heard-on-the-streets',
              name: 'Heard On The Streets',
              description: "<p>Description needed.</p>",
              thumb: '../../images/projects/12/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/12/001.jpg',
                '../../images/projects/12/002.jpg',
                '../../images/projects/12/003.jpg',
                '../../images/projects/12/004.jpg',
                '../../images/projects/12/005.jpg',
                '../../images/projects/12/006.jpg',
                '../../images/projects/12/007.jpg',
                '../../images/projects/12/008.jpg',
                '../../images/projects/12/009.jpg',
                '../../images/projects/12/010.jpg',
                '../../images/projects/12/011.jpg',
                '../../images/projects/12/012.jpg',
                '../../images/projects/12/013.jpg',
                '../../images/projects/12/014.jpg',
                '../../images/projects/12/015.jpg',
                '../../images/projects/12/016.jpg',
                '../../images/projects/12/017.jpg',
                '../../images/projects/12/018.jpg',
                '../../images/projects/12/019.jpg',
                '../../images/projects/12/020.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Heard On The Streets',
                  type : 'Show Package 1',
                  cover: '../../images/projects/12/004.jpg',
                },
                {
                  id : 2,
                  title : 'Heard On The Streets',
                  type : 'Show Package 3',
                  cover: '../../images/projects/12/004.jpg',
                }]
          },
          {
              id: 13,
              slug: 'i-am',
              name: 'I AM',
              description: "<p>A branding and photography project for a South African fashion label.</p>",
              thumb: '../../images/projects/13/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/13/001.jpg',
                '../../images/projects/13/002.jpg',
                '../../images/projects/13/003.jpg',
                '../../images/projects/13/004.jpg',
                '../../images/projects/13/005.jpg',
                '../../images/projects/13/006.jpg',
                '../../images/projects/13/007.jpg',
                '../../images/projects/13/008.jpg',
                '../../images/projects/13/009.jpg',
                '../../images/projects/13/010.jpg',
                '../../images/projects/13/011.jpg',
                '../../images/projects/13/012.jpg',
                '../../images/projects/13/013.png',
                '../../images/projects/13/014.jpg',
                '../../images/projects/13/015.jpg',
                '../../images/projects/13/016.jpg',
                '../../images/projects/13/017.jpg',
                '../../images/projects/13/018.jpg',
                '../../images/projects/13/019.jpg',
                '../../images/projects/13/020.jpg',
                '../../images/projects/13/021.jpg',
                '../../images/projects/13/022.jpg',
                '../../images/projects/13/023.jpg',
                '../../images/projects/13/024.jpg',
                '../../images/projects/13/025.jpg',
                '../../images/projects/13/026.jpg',
                '../../images/projects/13/027.jpg',
                '../../images/projects/13/028.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'I AM',
                  type : 'Show Package 1',
                  cover: '../../images/projects/13/015.jpg',
                },
                {
                  id : 2,
                  title : 'I AM',
                  type : 'Show Package 3',
                  cover: '../../images/projects/13/015.jpg',
                }]
          },
          {
              id: 14,
              slug: 'joy-of-jazz',
              name: 'Joy Of Jazz',
              description: "<p>Joy of Jazz 2014 artist line-up</p>",
              thumb: '../../images/projects/14/thumb.jpg',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/14/001.jpg',
                '../../images/projects/14/002.jpg',
                '../../images/projects/14/003.jpg',
                '../../images/projects/14/004.jpg',
                '../../images/projects/14/005.jpg',
                '../../images/projects/14/006.jpg',
                '../../images/projects/14/007.jpg',
                '../../images/projects/14/008.jpg',
                '../../images/projects/14/009.jpg',
                '../../images/projects/14/010.jpg',
                '../../images/projects/14/011.jpg',
                '../../images/projects/14/012.jpg',
                '../../images/projects/14/013.jpg',
                '../../images/projects/14/014.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Joy Of Jazz',
                  type : 'Show Package 1',
                  cover: '../../images/projects/14/001.jpg',
                },
                {
                  id : 2,
                  title : 'Joy Of Jazz',
                  type : 'Show Package 3',
                  cover: '../../images/projects/14/001.jpg',
                }]
          },
          {
              id: 15,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 16,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 17,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 18,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 19,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 20,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 21,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 22,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 23,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          },
          {
              id: 11,
              slug: 'grolsch',
              name: 'Grolsch',
              description: "<p>Description needed.</p>",
              thumb: 'http://placehold.it/500x500',
              agency: "<a href='#'>Some Agency Name</a>",
              collaborators: "<a href='#'>Stanley</a>, <a href='#'>Frikkie</a>",
              sound: "<a href='#'>Reggie</a>",
              images: [
                '../../images/projects/11/1.jpg',
                '../../images/projects/11/2.jpg',
                '../../images/projects/11/3.jpg',
                '../../images/projects/11/6.jpg',
                '../../images/projects/11/7.jpg',
                '../../images/projects/11/9.jpg',
                '../../images/projects/11/10.jpg',
                '../../images/projects/11/11.jpg',
                '../../images/projects/11/12.jpg',
                '../../images/projects/11/14.jpg',
                '../../images/projects/11/16.jpg',
                '../../images/projects/11/17.jpg',
                '../../images/projects/11/4.jpg',
                '../../images/projects/11/5.jpg',
                '../../images/projects/11/8.jpg',
                '../../images/projects/11/13.jpg',
                '../../images/projects/11/15.jpg',
              ],
              videos : [
                {
                  id : 1,
                  title : 'Grolsch',
                  type : 'Show Package 1',
                  cover: '../../images/projects/11/4.jpg',
                },
                {
                  id : 2,
                  title : 'Grolsch',
                  type : 'Show Package 3',
                  cover: '../../images/projects/11/4.jpg',
                }]
          }];
          return {
              list: function(){
                  return projects;
              },
              find: function(id){
                  return _.find(projects, function(project){
                    return project.id == id;
                  });
              }
          };
          /* jshint ignore:end */
        });

  })(); 